# envshield/core/generator.py
# Renders env.schema.toml into a typed, validated config module in the target language.
import json
import keyword
import re
from typing import Any, Dict

SUPPORTED_LANGUAGES = ("python", "typescript")

# --- Python (pydantic-settings) ---

_PYTHON_HEADER = (
    '"""\n'
    "AUTO-GENERATED by `envshield generate` — do not edit by hand.\n"
    "Source of truth: env.schema.toml. Regenerate with: envshield generate\n\n"
    "Requires: pip install pydantic pydantic-settings\n"
    '"""\n\n'
    "from pydantic import Field, SecretStr\n"
    "from pydantic_settings import BaseSettings, SettingsConfigDict\n\n\n"
)


def _python_field_name(key: str) -> str:
    """Converts a schema key (e.g. DATABASE_URL) into a valid Python identifier."""
    name = re.sub(r"\W", "_", key).lower()
    if not name or name[0].isdigit():
        name = f"_{name}"
    if keyword.iskeyword(name):
        name = f"{name}_"
    return name


def _infer_python_type_and_literal(default_value: str):
    """Maps a schema's string defaultValue to a Python type name + source literal."""
    if default_value.lower() in ("true", "false"):
        return "bool", str(default_value.lower() == "true")
    if re.fullmatch(r"-?\d+", default_value):
        return "int", default_value
    return "str", repr(default_value)


def _render_python_field(key: str, details: Dict[str, Any]) -> str:
    field = _python_field_name(key)
    description = details.get("description", "")
    is_secret = bool(details.get("secret", False))
    default_value = details.get("defaultValue")

    if default_value is None:
        py_type = "SecretStr" if is_secret else "str"
        default_arg = "..."
    elif is_secret:
        py_type = "SecretStr"
        default_arg = repr(str(default_value))
    else:
        py_type, default_arg = _infer_python_type_and_literal(str(default_value))

    return (
        f"    {field}: {py_type} = Field(\n"
        f"        {default_arg}, description={description!r}, alias={key!r}\n"
        f"    )"
    )


def _generate_python(schema: Dict[str, Any]) -> str:
    """
    Renders a schema dict into the source of a pydantic-settings module. Secret
    variables are typed as `SecretStr` so their values are masked in reprs, logs,
    and tracebacks by default.
    """
    lines = [
        _PYTHON_HEADER,
        "class Settings(BaseSettings):",
        '    """Typed, validated access to this project\'s environment variables."""',
        "",
        "    model_config = SettingsConfigDict(",
        '        env_file=".env", populate_by_name=True, extra="ignore"',
        "    )",
        "",
    ]

    if not schema:
        lines.append("    pass")
    else:
        field_lines = [
            _render_python_field(key, details) for key, details in schema.items()
        ]
        lines.append("\n\n".join(field_lines))

    lines.extend(["", "", "settings = Settings()", ""])
    return "\n".join(lines)


# --- TypeScript (zod) ---

_TS_HEADER = (
    "/**\n"
    " * AUTO-GENERATED by `envshield generate` — do not edit by hand.\n"
    " * Source of truth: env.schema.toml. Regenerate with: envshield generate\n"
    " *\n"
    " * Requires: npm install zod\n"
    " */\n"
    'import { z } from "zod";\n\n'
    "/** Wraps a secret value so it never prints, logs, or serializes in plain text. */\n"
    "class Secret<T> {\n"
    "  private _value: T;\n\n"
    "  constructor(value: T) {\n"
    "    this._value = value;\n"
    "  }\n\n"
    "  get value(): T {\n"
    "    return this._value;\n"
    "  }\n\n"
    "  toString(): string {\n"
    '    return "**********";\n'
    "  }\n\n"
    "  toJSON(): string {\n"
    '    return "**********";\n'
    "  }\n"
    "}\n\n"
)


def _infer_zod_type_and_default(default_value: str):
    """Maps a schema's string defaultValue to a zod type builder + source literal."""
    if default_value.lower() in ("true", "false"):
        return "z.coerce.boolean()", str(default_value.lower() == "true").lower()
    if re.fullmatch(r"-?\d+", default_value):
        return "z.coerce.number()", default_value
    return "z.string()", json.dumps(default_value)


def _render_ts_field(key: str, details: Dict[str, Any]) -> str:
    description = details.get("description", "")
    default_value = details.get("defaultValue")

    if default_value is None:
        zod_type = "z.string().min(1)"
    else:
        base_type, default_literal = _infer_zod_type_and_default(str(default_value))
        zod_type = f"{base_type}.default({default_literal})"

    comment = f"  /** {description} */\n" if description else ""
    return f"{comment}  {json.dumps(key)}: {zod_type},"


def _generate_typescript(schema: Dict[str, Any]) -> str:
    """
    Renders a schema dict into a zod-validated TypeScript module. Secret variables
    are wrapped in a local `Secret<T>` type so their values are masked wherever
    they'd otherwise leak (`console.log`, template strings, `JSON.stringify`).
    """
    lines = [_TS_HEADER]

    if not schema:
        lines.append("const _schema = z.object({});")
    else:
        field_lines = [_render_ts_field(key, details) for key, details in schema.items()]
        lines.append("const _schema = z.object({\n" + "\n".join(field_lines) + "\n});")

    lines.extend(["", "const _parsed = _schema.parse(process.env);", ""])

    secret_keys = {key for key, details in schema.items() if details.get("secret")}
    export_lines = []
    for key in schema:
        prop = json.dumps(key)
        if key in secret_keys:
            export_lines.append(f"  {prop}: new Secret(_parsed[{prop}]),")
        else:
            export_lines.append(f"  {prop}: _parsed[{prop}],")

    if export_lines:
        lines.append("export const env = {\n" + "\n".join(export_lines) + "\n};")
    else:
        lines.append("export const env = _parsed;")
    lines.append("")

    return "\n".join(lines)


_GENERATORS = {
    "python": _generate_python,
    "typescript": _generate_typescript,
}


def generate_config(schema: Dict[str, Any], lang: str = "python") -> str:
    """
    Renders `schema` (as loaded from env.schema.toml) into the source of a typed,
    validated config module in the requested language. Secret variables are
    masked by default in the generated code's runtime representation.
    """
    try:
        render = _GENERATORS[lang]
    except KeyError:
        raise ValueError(
            f"Unsupported language {lang!r}. Supported: {', '.join(SUPPORTED_LANGUAGES)}"
        )
    return render(schema)
