# envshield/core/generator.py
# Renders env.schema.toml into a typed, validated config module in the target language.
import json
import keyword
import re
from typing import Any

from . import schema_types

SUPPORTED_LANGUAGES = ("python", "typescript")

# --- Python (pydantic-settings) ---

_PYTHON_HEADER_TEMPLATE = (
    '"""\n'
    "AUTO-GENERATED by `envshield generate` — do not edit by hand.\n"
    "Source of truth: env.schema.toml. Regenerate with: envshield generate\n\n"
    "Requires: pip install pydantic pydantic-settings{extra_requires}\n"
    '"""\n\n'
    "{extra_imports}"
    "from pydantic import Field, SecretStr\n"
    "from pydantic_settings import BaseSettings, SettingsConfigDict\n\n\n"
)


def _python_field_name(key: str) -> str:
    """Converts a schema key (e.g. DATABASE_URL) into a valid Python identifier."""
    name = re.sub(r"\W", "_", key).lower()
    if not name or name[0].isdigit():
        name = f"_{name}"
    if keyword.iskeyword(name):
        name = f"{name}_"
    return name


def _effective_field_type(details: dict[str, Any]) -> str:
    """
    The type category driving codegen: the schema's explicit 'type' or
    'enum' when given, otherwise inferred from defaultValue's own shape
    (legacy behavior, unchanged), otherwise plain 'string'. See this
    module's docstring reference in schema_types for why this differs from
    schema_types.resolve_field_type (used for *validating* real values).
    """
    if details.get("enum"):
        return "enum"
    declared = details.get("type")
    if declared:
        return declared
    default_value = details.get("defaultValue")
    if default_value is not None:
        dv = str(default_value)
        if dv.lower() in ("true", "false"):
            return "bool"
        if re.fullmatch(r"-?\d+", dv):
            return "int"
    return "string"


def _default_literal(field_type: str, default_value: str) -> str:
    """Renders a schema defaultValue as a Python literal matching `field_type`."""
    if field_type in ("int", "port") and re.fullmatch(r"-?\d+", default_value):
        return default_value
    if field_type == "float":
        try:
            float(default_value)
            return default_value
        except ValueError:
            pass
    if field_type == "bool":
        return str(default_value.lower() == "true")
    return repr(default_value)


def _python_type_and_extras(
    field_type: str, details: dict[str, Any]
) -> tuple[str, list[str], set[str]]:
    """Returns (type name, extra Field()-kwargs, extra imports) for a non-secret field's declared type."""
    if field_type == "enum":
        values = schema_types.enum_values(details)
        literal = ", ".join(repr(v) for v in values)
        return f"Literal[{literal}]", [], {"from typing import Literal"}
    if field_type == "int":
        return "int", [], set()
    if field_type == "float":
        return "float", [], set()
    if field_type == "bool":
        return "bool", [], set()
    if field_type == "port":
        return "int", ["ge=1", "le=65535"], set()
    if field_type == "url":
        return "AnyUrl", [], {"from pydantic import AnyUrl"}
    if field_type == "email":
        return "EmailStr", [], {"from pydantic import EmailStr"}

    pattern = details.get("pattern")
    extra_kwargs = [f"pattern={pattern!r}"] if pattern else []
    return "str", extra_kwargs, set()


def _render_python_field(key: str, details: dict[str, Any]) -> tuple[str, set[str]]:
    field = _python_field_name(key)
    description = details.get("description", "")
    is_secret = bool(details.get("secret", False))
    default_value = details.get("defaultValue")
    field_type = _effective_field_type(details)

    imports: set[str] = set()
    extra_kwargs: list[str] = []

    if is_secret:
        # A masked SecretStr always wins over a declared type -- pydantic's
        # SecretStr is string-specific, so "secret + type=int" etc. would be
        # a contradiction. The secret flag is the stronger guarantee.
        py_type = "SecretStr"
    else:
        py_type, extra_kwargs, imports = _python_type_and_extras(field_type, details)

    # A field with 'requiredIf' and no default is only sometimes required --
    # codegen can't evaluate that condition ahead of time, so it's typed as
    # optional; 'check'/'doctor' enforce the real, conditional requirement
    # at validation time against the project's actual local values.
    conditional = "requiredIf" in details and default_value is None
    if conditional:
        py_type = f"Optional[{py_type}]"
        imports.add("from typing import Optional")

    if default_value is None:
        default_arg = "None" if conditional else "..."
    elif is_secret:
        default_arg = repr(str(default_value))
    else:
        default_arg = _default_literal(field_type, str(default_value))

    kwargs_str = "".join(f", {kw}" for kw in extra_kwargs)
    rendered = f"    {field}: {py_type} = Field(\n        {default_arg}, description={description!r}, alias={key!r}{kwargs_str}\n    )"
    return rendered, imports


def _generate_python(schema: dict[str, Any]) -> str:
    """
    Renders a schema dict into the source of a pydantic-settings module. Secret
    variables are typed as `SecretStr` so their values are masked in reprs, logs,
    and tracebacks by default. Fields with an explicit 'type'/'enum'/'pattern'
    get the matching pydantic type and constraint.
    """
    field_lines: list[str] = []
    all_imports: set[str] = set()
    for key, details in schema.items():
        rendered, imports = _render_python_field(key, details)
        field_lines.append(rendered)
        all_imports.update(imports)

    needs_email = "from pydantic import EmailStr" in all_imports
    extra_requires = (
        " (and 'pydantic[email]' if any field uses type = \"email\")"
        if needs_email
        else ""
    )

    ordered_imports = sorted(all_imports)
    header = _PYTHON_HEADER_TEMPLATE.format(
        extra_requires=extra_requires,
        extra_imports=("".join(f"{imp}\n" for imp in ordered_imports) + "\n")
        if ordered_imports
        else "",
    )

    lines = [
        header,
        "class Settings(BaseSettings):",
        '    """Typed, validated access to this project\'s environment variables."""',
        "",
        "    model_config = SettingsConfigDict(",
        '        env_file=".env", populate_by_name=True, extra="ignore"',
        "    )",
        "",
    ]

    if not schema:
        lines.append("    pass")
    else:
        lines.append("\n\n".join(field_lines))

    lines.extend(["", "", "settings = Settings()", ""])
    return "\n".join(lines)


# --- TypeScript (zod) ---

_TS_HEADER = (
    "/**\n"
    " * AUTO-GENERATED by `envshield generate` — do not edit by hand.\n"
    " * Source of truth: env.schema.toml. Regenerate with: envshield generate\n"
    " *\n"
    " * Requires: npm install zod\n"
    " */\n"
    'import { z } from "zod";\n\n'
    "/**\n"
    " * Wraps a secret value so it's masked in template strings (toString),\n"
    " * JSON.stringify (toJSON), and default console.log/util.inspect output.\n"
    " *\n"
    " * The backing field uses real EcmaScript private-field syntax (`#value`),\n"
    " * not TypeScript's `private` keyword -- `private` is a compile-time-only\n"
    " * annotation that still emits a plain, enumerable runtime property, which\n"
    " * would leak in full on a bare `console.log(secret)`. `#value` is a true\n"
    " * private slot: it's invisible to Object.keys/JSON.stringify/for...in and\n"
    " * to Node's default object inspection, so accessing the real value always\n"
    " * requires the explicit `.value` getter below.\n"
    " */\n"
    "class Secret<T> {\n"
    "  #value: T;\n\n"
    "  constructor(value: T) {\n"
    "    this.#value = value;\n"
    "  }\n\n"
    "  get value(): T {\n"
    "    return this.#value;\n"
    "  }\n\n"
    "  toString(): string {\n"
    '    return "**********";\n'
    "  }\n\n"
    "  toJSON(): string {\n"
    '    return "**********";\n'
    "  }\n\n"
    '  [Symbol.for("nodejs.util.inspect.custom")](): string {\n'
    '    return "Secret(**********)";\n'
    "  }\n"
    "}\n\n"
)


def _zod_base_type(field_type: str, details: dict[str, Any]) -> str:
    """The zod builder expression for a field's declared type, before '.default()'/'.optional()' is appended."""
    if field_type == "enum":
        values = schema_types.enum_values(details)
        literal = ", ".join(json.dumps(v) for v in values)
        return f"z.enum([{literal}])"
    if field_type in ("int", "float"):
        return "z.coerce.number()"
    if field_type == "bool":
        return "z.coerce.boolean()"
    if field_type == "port":
        return "z.coerce.number().min(1).max(65535)"
    if field_type == "url":
        return "z.string().url()"
    if field_type == "email":
        return "z.string().email()"

    base = "z.string()"
    pattern = details.get("pattern")
    if pattern:
        base += f".regex(new RegExp({json.dumps(pattern)}))"
    return base


def _zod_default_literal(field_type: str, default_value: str) -> str:
    """Renders a schema defaultValue as a JS literal for zod's '.default(...)'."""
    if field_type in ("int", "port") and re.fullmatch(r"-?\d+", default_value):
        return default_value
    if field_type == "float":
        try:
            float(default_value)
            return default_value
        except ValueError:
            pass
    if field_type == "bool":
        return str(default_value.lower() == "true").lower()
    return json.dumps(default_value)


def _render_ts_field(key: str, details: dict[str, Any]) -> str:
    description = details.get("description", "")
    default_value = details.get("defaultValue")
    field_type = _effective_field_type(details)
    conditional = "requiredIf" in details and default_value is None
    has_pattern = bool(details.get("pattern"))

    if (
        field_type == "string"
        and default_value is None
        and not has_pattern
        and not conditional
    ):
        # Preserve the exact legacy shape for a plain required string with no constraints.
        zod_type = "z.string().min(1)"
    else:
        zod_type = _zod_base_type(field_type, details)
        if default_value is not None:
            zod_type += (
                f".default({_zod_default_literal(field_type, str(default_value))})"
            )
        elif conditional:
            # Same reasoning as the Python side: codegen can't evaluate a
            # 'requiredIf' condition ahead of time, so the field is optional
            # here; 'check'/'doctor' enforce the real requirement at runtime.
            zod_type += ".optional()"
        elif field_type == "string":
            # A required plain string with only a pattern constraint still
            # needs the same non-empty guarantee '.min(1)' gives by default.
            zod_type += ".min(1)"

    comment = f"  /** {description} */\n" if description else ""
    return f"{comment}  {json.dumps(key)}: {zod_type},"


def _generate_typescript(schema: dict[str, Any]) -> str:
    """
    Renders a schema dict into a zod-validated TypeScript module. Secret variables
    are wrapped in a local `Secret<T>` type so their values are masked wherever
    they'd otherwise leak (`console.log`, template strings, `JSON.stringify`).
    """
    lines = [_TS_HEADER]

    if not schema:
        lines.append("const _schema = z.object({});")
    else:
        field_lines = [
            _render_ts_field(key, details) for key, details in schema.items()
        ]
        lines.append("const _schema = z.object({\n" + "\n".join(field_lines) + "\n});")

    lines.extend(["", "const _parsed = _schema.parse(process.env);", ""])

    secret_keys = {key for key, details in schema.items() if details.get("secret")}
    export_lines = []
    for key in schema:
        prop = json.dumps(key)
        if key in secret_keys:
            export_lines.append(f"  {prop}: new Secret(_parsed[{prop}]),")
        else:
            export_lines.append(f"  {prop}: _parsed[{prop}],")

    if export_lines:
        lines.append("export const env = {\n" + "\n".join(export_lines) + "\n};")
    else:
        lines.append("export const env = _parsed;")
    lines.append("")

    return "\n".join(lines)


_GENERATORS = {
    "python": _generate_python,
    "typescript": _generate_typescript,
}


def generate_config(schema: dict[str, Any], lang: str = "python") -> str:
    """
    Renders `schema` (as loaded from env.schema.toml) into the source of a typed,
    validated config module in the requested language. Secret variables are
    masked by default in the generated code's runtime representation.
    """
    try:
        render = _GENERATORS[lang]
    except KeyError:
        raise ValueError(
            f"Unsupported language {lang!r}. Supported: {', '.join(SUPPORTED_LANGUAGES)}"
        )
    return render(schema)
