# envshield/core/importer.py
import os
import re
from typing import Any, Dict, Optional, Tuple
from urllib.parse import urlparse

import questionary
import toml
from rich.console import Console

from ..parsers._dotenv import DotenvParser
from ..parsers.factory import get_parser
from . import discovery
from .exceptions import EnvShieldException
from .scanner import MAX_SCANNABLE_SIZE_BYTES, SECRET_PATTERNS

_EMAIL_RE = re.compile(r"^[^@\s]+@[^@\s]+\.[^@\s]+$")

console = Console()

SCHEMA_HEADER = (
    "# This schema was auto-generated by 'envshield import'\n"
    "# Please review and add descriptions for each variable.\n\n"
)

# Heuristics for smarter import
SECRET_KEY_KEYWORDS = ["secret", "token", "password", "key", "auth", "credential"]

# Naming conventions several frontend frameworks use to mark an env var as
# intentionally public: these get inlined straight into the client-side
# bundle at build time, so by design they are never secret -- regardless of
# what their name happens to contain (a Stripe *publishable* key legitimately
# has "key" in its name, e.g. NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY).
PUBLIC_KEY_PREFIXES = (
    "NEXT_PUBLIC_",  # Next.js
    "VITE_",  # Vite
    "REACT_APP_",  # Create React App
    "NUXT_PUBLIC_",  # Nuxt 3
    "PUBLIC_",  # SvelteKit
    "GATSBY_",  # Gatsby
)

# Specific well-known variable names that are public by convention even
# though the name alone would otherwise look secret-ish -- e.g. dotenvx's
# own encryption metadata variable, which holds a *public* key.
KNOWN_PUBLIC_VAR_NAMES = {"DOTENV_PUBLIC_KEY"}


def key_contains_secret_keyword(key: str, keywords=SECRET_KEY_KEYWORDS) -> bool:
    """
    Checks whether any '_'-delimited token in `key` matches a secret keyword.

    Token-based (not substring) matching avoids false positives on compound
    names that merely *contain* a keyword as a substring -- e.g. MONKEY_PATCH
    contains "key" and AUTHOR_NAME contains "auth", but neither is a secret.
    """
    tokens = key.lower().split("_")
    return any(keyword in tokens for keyword in keywords)


def _is_conventionally_public(key: str) -> bool:
    """
    True for a variable that's public by a well-known naming convention.
    Doesn't override a high-confidence match against an actual secret-shaped
    *value* -- see _classify_variable -- so a real secret accidentally
    placed under e.g. a NEXT_PUBLIC_ name is still flagged.
    """
    if key in KNOWN_PUBLIC_VAR_NAMES:
        return True
    return key.upper().startswith(PUBLIC_KEY_PREFIXES)


def _classify_variable(key: str, value: str) -> Tuple[bool, Any]:
    """
    Intelligently classifies a variable as a secret and suggests a default value.

    Returns:
        A tuple of (is_secret: bool, default_value: Any | None).
    """
    # 1. Check value against high-confidence secret patterns first -- this
    # always wins, even for a conventionally-public name.
    for secret in SECRET_PATTERNS:
        if re.search(secret["pattern"], value):
            return True, None

    # 2. A conventionally-public name is never treated as secret from its
    # name alone -- skip the keyword heuristic entirely for these.
    if _is_conventionally_public(key):
        return False, value or None

    # 3. Check the key for common secret-indicating keywords
    if key_contains_secret_keyword(key):
        return True, None

    # 4. Anything else with a concrete value already sitting in the source
    # file is worth suggesting as the default -- it's already committed (or
    # already on this developer's disk) and isn't keyword-flagged as a
    # secret, so carrying it forward as a schema default doesn't expose
    # anything new. This used to be limited to a small hardcoded whitelist
    # of variable names (DEBUG, LOG_LEVEL, PORT, HOST, ...), which missed
    # every project-specific non-secret var -- e.g. a Flask app's
    # `DB_NAME = "alpha"` or `CACHE_PORT = 6379` got no suggested default
    # at all, just because the name wasn't on the list.
    if value:
        return False, value

    # 5. Blank value, no other signal: genuinely undetermined.
    return False, None


def _infer_type(key: str, value: str) -> Optional[str]:
    """
    Best-effort guess at a non-secret variable's schema `type`, from the
    shape of its one sample value -- so a freshly-imported schema starts
    with real type/format constraints (see schema_types.py) instead of
    every variable defaulting to an unconstrained plain string that has to
    be typed in by hand later. Only confident, unambiguous shapes are
    inferred; anything else is left alone rather than guessed at.
    """
    if not value:
        return None
    if re.fullmatch(r"-?\d+", value):
        return "port" if "port" in key.lower().split("_") else "int"
    if value.lower() in ("true", "false"):
        return "bool"
    parsed = urlparse(value)
    if parsed.scheme and parsed.netloc:
        return "url"
    if _EMAIL_RE.match(value):
        return "email"
    return None


def _is_oversized_for_default(value: str) -> bool:
    """
    True when `value` is too large to responsibly suggest as a schema
    `defaultValue` -- reuses scan's own file-size threshold (see
    MAX_SCANNABLE_SIZE_BYTES) rather than a second, independently-chosen
    limit, since the underlying concern is the same one scan already
    guards against: fully embedding something this large into a generated
    artifact. Secret classification/type inference are untouched by this
    -- they still see the real value; only the *defaultValue write* is
    gated, and only for a value that would otherwise be suggested as one
    (a secret's default is already withheld unconditionally by
    _classify_variable, oversized or not).
    """
    return len(value) > MAX_SCANNABLE_SIZE_BYTES


def _discover_python_variables(
    file_path: str, as_local_values: bool = False
) -> Dict[str, str]:
    """
    Variable discovery for a '.py' source, specifically for
    generate_schema_from_file/merge_variables_from_other_sources -- NOT
    the general '.py' parser used everywhere else in this codebase
    (get_parser/PythonParser), which reads EnvShield's OWN local config
    module format (env_config.local.py-style, where a top-level assignment
    IS the real, final value) and must stay exactly as-is for its own,
    different, already-correct callers (setup_manager, schema_manager,
    doctor, explain, service_discovery).

    `as_local_values=True` says the caller already knows this file's
    role: it is being registered as (or seeded from) a service's own
    local values file, the exact format PythonParser reads. The content
    heuristic below is then not merely unnecessary but wrong -- whatever
    it decides, every command that later consumes this file
    ('check'/'doctor'/'setup'/'schema sync') will read it with
    PythonParser, so seeding the schema any other way defines the same
    file's configuration surface twice, incompatibly. A real config-as-
    code module (dozens of literal assignments, plus a couple of
    `os.environ` reads guarding local overrides) is exactly where the
    two rules diverge hardest, and it is precisely the shape
    service_discovery recognises as a config module in the first place
    -- using PythonParser's own definition to do so. Role beats
    guessing: this parameter carries the decision that was already made
    rather than re-deriving a different one from the bytes.

    Prefers discovery.discover_python_env_vars -- the same AST engine
    'undeclared'/'explain' use for real os.environ.get/os.getenv/
    os.environ[] reads (correct at any nesting depth, including inside a
    class body), plus BaseSettings field recognition -- whenever it finds
    at least one recognized read anywhere in the file. Falls back to the
    existing PythonParser-based top-level-literal scan, completely
    unchanged, only when it finds none at all: a file with zero recognized
    environment reads is, by that same signal, indistinguishable from a
    plain, already-resolved local config module (exactly what
    PythonParser was built for) -- and importing one that way is a real,
    tested, still-supported use of 'import' today, deliberately preserved
    rather than solved here (a real settings file with framework noise but
    zero env reads at all would still show that noise; there's nothing
    else to fall back to, and nothing meaningful to discover).

    Deduplicates by the discovered variable name (not the Python
    assignment target it happened to be read into) -- first occurrence's
    recovered default wins; a later occurrence of the same name never
    overwrites it, and conflicting defaults between reads are never
    reconciled.
    """
    if as_local_values:
        parser = get_parser(file_path)
        return parser.get_vars(file_path, get_values=True) if parser else {}

    with open(file_path, "r") as f:
        content = f.read()

    discovered = discovery.discover_python_env_vars(content, file_path)
    if not discovered:
        parser = get_parser(file_path)
        return parser.get_vars(file_path, get_values=True) if parser else {}

    variables: Dict[str, str] = {}
    for usage in discovered:
        if usage.variable in variables:
            continue
        variables[usage.variable] = usage.default_value or ""
    return variables


def generate_schema_from_file(
    file_path: str,
    interactive: bool = False,
    existing_schema: Optional[Dict[str, Any]] = None,
    as_local_values: bool = False,
) -> str:
    """
    Reads an environment file and generates a TOML schema string, with an
    optional interactive mode for refinement.

    `existing_schema`, when given, is merged in additively: a variable
    already declared there but missing from this scan (e.g. a
    locally-drifted '.env' that stopped mentioning it) is always kept
    exactly as-is -- a re-scan should never silently discard a variable
    that's already declared, interactive or not.

    For a variable this scan DID find that's also already declared,
    behavior depends on `interactive`: non-interactively, the existing
    declaration still wins outright over this scan's reclassification --
    a hand-picked correction (a fixed `secret` flag, an added `pattern`)
    has to survive an unreviewed re-run. Interactively, the user was just
    asked about that exact variable above, so their live answer wins
    instead -- keeping the stale existing entry would defeat the entire
    point of `--interactive` re-classification.

    `as_local_values` is passed through to `_discover_python_variables`
    for a '.py' source: set it when this file is the service's own local
    values file, so the schema is seeded from the same configuration
    surface every command that later reads that file will see. It has no
    effect on any other file format -- a dotenv file or a deployment
    manifest has only ever had one reading.
    """
    if not os.path.exists(file_path):
        raise EnvShieldException(f"Input file not found at: {file_path}")

    commented_out_count = 0
    if file_path.endswith(".py"):
        variables = _discover_python_variables(file_path, as_local_values)
    else:
        parser = get_parser(file_path)
        if not parser:
            raise EnvShieldException(
                f"Could not find a suitable parser for '{file_path}'. "
                "Supported: a dotenv file (.env or no extension), a Python module (.py), "
                "or a docker-compose/Kubernetes YAML manifest."
            )
        variables = parser.get_vars(file_path, get_values=True)
        if isinstance(parser, DotenvParser):
            commented_out_count = DotenvParser.count_commented_out_assignments(
                file_path
            )

    schema_dict: Dict[str, Any] = {}
    secrets_found = 0
    defaults_found = 0
    types_found = 0
    oversized_defaults: list = []

    console.print("\n[bold]Analyzing variables...[/bold]")

    for key, value in variables.items():
        is_secret, default_value = _classify_variable(key, value)
        # Inferring a type is safe regardless of secret status -- it only
        # records the *shape* a valid value must have (e.g. type = "url"),
        # never the value itself. defaultValue is the one field that would
        # actually leak a secret's value, and that's already withheld
        # below/via _classify_variable (a secret classification always
        # returns default_value=None) -- so there's nothing this loses by
        # inferring type unconditionally, and a secret field otherwise got
        # zero shape validation at all.
        inferred_type = _infer_type(key, value)

        if interactive:
            console.print(
                f"\nVariable [bold cyan]{key}[/bold cyan] = [dim]'{value}'[/dim]"
            )
            is_secret = questionary.confirm(
                "  Mark as a secret?", default=is_secret
            ).ask()
            if not is_secret:
                use_default = questionary.confirm(
                    f"  Use '{value}' as the default value?",
                    default=(default_value is not None),
                ).ask()
                if use_default:
                    default_value = value
                else:
                    default_value = None

        schema_dict[key] = {"description": "TODO: Add description."}
        if is_secret:
            schema_dict[key]["secret"] = True
            secrets_found += 1
        else:
            schema_dict[key]["secret"] = False
            if default_value is not None:
                # An oversized value is never written into the schema, not
                # even truncated -- the variable itself is still kept (it
                # was already added above, just without a defaultValue),
                # since classification/type-inference above didn't need
                # the value to fit in memory-friendly form to run.
                if _is_oversized_for_default(default_value):
                    oversized_defaults.append(key)
                else:
                    schema_dict[key]["defaultValue"] = default_value
                    defaults_found += 1
        if inferred_type:
            schema_dict[key]["type"] = inferred_type
            types_found += 1

    preserved = 0
    if existing_schema:
        # 'extends' is a top-level composition directive, not a variable --
        # carried over as-is rather than through the per-variable loop
        # below, and never something a value-scan could rediscover on its
        # own if dropped.
        if "extends" in existing_schema:
            schema_dict["extends"] = existing_schema["extends"]
        for key, details in existing_schema.items():
            if key == "extends":
                continue
            if key not in schema_dict:
                # Missing from this scan entirely (e.g. a drifted source
                # that stopped mentioning it) -- always preserved,
                # interactive or not, since there's nothing fresh to
                # weigh it against.
                preserved += 1
                schema_dict[key] = details
            elif not interactive:
                # A non-interactive re-scan doesn't get final say: the
                # existing declaration wins outright even though this scan
                # also found the variable and would otherwise reclassify
                # it -- a hand-picked correction (a fixed 'secret' flag, an
                # added 'pattern') has to survive an unreviewed re-run.
                schema_dict[key] = details
            # else: interactive mode, and the user was just asked about
            # this exact variable above -- their live answer wins. Falling
            # back to the stale existing entry here would silently discard
            # the very re-classification '--interactive' exists to do.

    console.print("\n[bold green]✓ Analysis complete![/bold green]")
    console.print(f"- Processed {len(variables)} variables.")
    console.print(f"- Marked {secrets_found} variable(s) as secrets.")
    console.print(f"- Suggested {defaults_found} default value(s).")
    if preserved:
        console.print(
            f"- Kept {preserved} existing variable(s) not found in this scan, unchanged."
        )
    console.print(
        f"- Inferred a type (int/port/bool/url/email) for {types_found} variable(s)."
    )
    if commented_out_count:
        console.print(
            f"[bold yellow]Warning:[/] Found {commented_out_count} commented-out "
            "variable assignment(s); these were not imported."
        )
    if oversized_defaults:
        console.print(
            f"[bold yellow]Warning:[/] Skipped {len(oversized_defaults)} value(s) "
            f"over {MAX_SCANNABLE_SIZE_BYTES // 1_000_000}MB as a suggested "
            "default (variable(s) kept without one): "
            + ", ".join(sorted(oversized_defaults))
        )

    return SCHEMA_HEADER + toml.dumps(schema_dict)


def merge_variables_from_other_sources(
    schema_dict: Dict[str, Any], other_sources: list
) -> Dict[str, list]:
    """
    Adds any variable found in `other_sources` (see
    service_discovery.find_other_config_sources) that isn't already in
    `schema_dict`, classified the same way generate_schema_from_file
    classifies its own primary source.

    A pinned config_source is only ever re-scanned itself -- it has no way
    to notice a variable added straight to some OTHER real config file
    sitting right next to it (e.g. a Python config module gaining a var a
    stale '.env' never picked up). This closes that gap at 'init' time,
    additively only: a key already in `schema_dict` is never touched here,
    whether it came from the primary source or a previous call.

    Returns {source_path: [added_key, ...]} for whichever sources actually
    contributed something, so the caller can report exactly what happened.
    """
    added: Dict[str, list] = {}
    for path in other_sources:
        try:
            if path.endswith(".py"):
                variables = _discover_python_variables(path)
            else:
                parser = get_parser(path)
                if not parser:
                    continue
                variables = parser.get_vars(path, get_values=True)
        except (FileNotFoundError, OSError, EnvShieldException):
            # A malformed "other source" is skipped, not fatal to the merge
            # -- one bad file must not stop the remaining sources from
            # contributing their own variables (see BL-002).
            continue

        for key, value in variables.items():
            if key in schema_dict:
                continue
            is_secret, default_value = _classify_variable(key, value)
            inferred_type = _infer_type(key, value)

            entry: Dict[str, Any] = {"description": "TODO: Add description."}
            entry["secret"] = is_secret
            if (
                not is_secret
                and default_value is not None
                and not _is_oversized_for_default(default_value)
            ):
                entry["defaultValue"] = default_value
            if inferred_type:
                entry["type"] = inferred_type

            schema_dict[key] = entry
            added.setdefault(path, []).append(key)

    return added
