# envshield/core/schema_manager.py
import datetime
import os
from typing import Any, Dict, Optional

from rich.console import Console
from rich.table import Table

from envshield.config import manager as config_manager
from envshield.core import file_updater
from envshield.parsers.factory import get_parser

console = Console()


def check_schema(file_path: str, service_name: Optional[str] = None) -> bool:
    """
    Validates a local environment file against the env.schema.toml,
    intelligently handling variables with default values.

    If `service_name` is provided, validates against that service's schema.
    Otherwise, validates against the root schema.

    Returns:
        True if the local file is in sync with the schema, False otherwise
        (including when the file or a usable parser can't be found).
    """
    console.print(
        f"\n[bold]Validating [magenta]{file_path}[/magenta] against schema...[/bold]"
    )

    # Load the schema and the local .env file
    schema = config_manager.load_schema(service_name=service_name)
    parser = get_parser(file_path)

    if not parser:
        console.print(f"[red]Error:[/red] No parser found for file type '{file_path}'.")
        return False

    try:
        local_values = parser.get_vars(file_path, get_values=True)
    except FileNotFoundError:
        console.print(f"[red]Error:[/red] File not found: '{file_path}'.")
        return False

    local_vars = set(local_values.keys())

    # Get all variables defined in the schema
    schema_vars_all = set(schema.keys())

    # A variable is only considered "required" in the local file if it's in the schema
    # AND it does NOT have a defaultValue.
    schema_vars_required = {
        key for key, details in schema.items() if "defaultValue" not in details
    }

    # A required var declared only as a blank placeholder (e.g.
    # `SECRETS_ENCRYPTION_KEY = ""` checked in ahead of a real per-developer
    # secret) is just as incomplete as one missing outright -- checking only
    # for the key's presence let this go undetected until it broke at
    # runtime. Distinguish the two so the report is precise about which.
    missing_in_local = set()
    blank_in_local = set()
    for key in schema_vars_required:
        if key not in local_values:
            missing_in_local.add(key)
        elif not local_values[key]:
            blank_in_local.add(key)

    extra_in_local = local_vars - schema_vars_all

    if not missing_in_local and not blank_in_local and not extra_in_local:
        console.print(
            "[bold green]✓ Your configuration is perfectly in sync with the schema![/bold green]"
        )
        return True

    # If there are issues, build and display a report table
    table = Table(show_header=True, header_style="bold blue")
    table.add_column("Status", style="cyan")
    table.add_column("Variable Name", style="white")
    table.add_column("Source", style="white")

    for var in sorted(missing_in_local):
        table.add_row("[red]Missing in Local[/red]", var, "env.schema.toml (Required)")

    for var in sorted(blank_in_local):
        table.add_row("[red]Blank in Local[/red]", var, "env.schema.toml (Required)")

    for var in sorted(extra_in_local):
        table.add_row("[yellow]Extra in Local[/yellow]", var, file_path)

    console.print(table)
    console.print(
        "\n[bold]Suggestion:[/bold] Please update your local file to match the schema contract."
    )
    return False


def sync_schema(service_name: Optional[str] = None):
    """
    Keeps a service's tracked environment template in sync with its schema.

    Dotenv projects (the default) get '.env.example' fully regenerated from
    the schema -- it's a pure generated artifact, safe to overwrite wholesale.

    Projects whose local config is a Python module (`local_file` ends in
    '.py' -- e.g. zeus's `env_config.local.py`) have no such artifact: that
    file IS the hand-maintained contract, often with logic beyond simple
    assignments. So instead of overwriting it, this only appends whatever
    schema variables are missing from it; existing lines, values, and
    surrounding code are left untouched.

    If `service_name` is provided, syncs that service's schema and template
    (resolved to that service's own directory, see config_manager.get_env_paths).
    Otherwise, syncs the root project's schema and '.env.example'.
    """
    schema = config_manager.load_schema(service_name=service_name)
    paths = config_manager.get_env_paths(service_name=service_name)

    if paths["local_file"].endswith(".py"):
        _sync_python_local_file(schema, paths["local_file"])
        return

    output_file = paths["example_file"]
    console.print(f"\n[bold]Generating [cyan]{output_file}[/cyan] from schema...[/bold]")

    header = (
        f"# This file was auto-generated by EnvShield on {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n"
        f"# It is generated from the contract defined in env.schema.toml.\n"
        f"# DO NOT EDIT THIS FILE MANUALLY.\n\n"
    )

    content = header
    for key, details in schema.items():
        description = details.get("description")
        if description:
            content += f"# {description}\n"

        default_value = details.get("defaultValue", "")
        content += f"{key}={default_value}\n\n"

    try:
        output_dir = os.path.dirname(output_file)
        if output_dir:
            os.makedirs(output_dir, exist_ok=True)
        with open(output_file, "w") as f:
            f.write(content)
        console.print(
            f"[bold green]✓[/bold green] Successfully created/updated [bold cyan]{output_file}[/bold cyan]!"
        )
    except IOError as e:
        console.print(f"[red]Error:[/red] Could not write to {output_file}: {e}")


def _sync_python_local_file(schema: Dict[str, Any], local_file: str) -> None:
    """Ensures a Python-module local config file declares every schema variable."""
    if not os.path.exists(local_file):
        console.print(f"\n[bold]Creating [cyan]{local_file}[/cyan] from schema...[/bold]")
        lines = [
            "# Auto-generated by 'envshield schema sync'.\n",
            "# Fill in real values below -- this file is your project's local config module.\n\n",
        ]
        for key, details in schema.items():
            description = details.get("description")
            if description:
                lines.append(f"# {description}\n")
            lines.append(f"{key} = {str(details.get('defaultValue', ''))!r}\n\n")

        output_dir = os.path.dirname(local_file)
        if output_dir:
            os.makedirs(output_dir, exist_ok=True)
        with open(local_file, "w") as f:
            f.writelines(lines)
        console.print(f"[bold green]✓[/bold green] Created [bold cyan]{local_file}[/bold cyan]!")
        return

    console.print(f"\n[bold]Checking [cyan]{local_file}[/cyan] for missing variables...[/bold]")
    parser = get_parser(local_file)
    existing_vars = parser.get_vars(local_file) if parser else set()
    missing = {key: details for key, details in schema.items() if key not in existing_vars}

    if not missing:
        console.print(
            f"[bold green]✓[/bold green] [cyan]{local_file}[/cyan] already declares every schema variable."
        )
        return

    updates = [
        {"key": key, "value": str(details.get("defaultValue", ""))}
        for key, details in missing.items()
    ]
    file_updater.update_variables_in_file(local_file, updates)
    console.print(
        f"[bold green]✓[/bold green] Added {len(updates)} missing variable(s) to "
        f"[bold cyan]{local_file}[/bold cyan]: {', '.join(missing.keys())}"
    )
