# envshield/tests/core/test_schema_manager.py
import os

from typer.testing import CliRunner

from envshield.core import schema_manager

runner = CliRunner()


def test_check_schema_in_sync(mocker, tmp_path):
    """Tests the check command when the local file is in sync with the schema."""
    with runner.isolated_filesystem(temp_dir=tmp_path):
        mocker.patch(
            "envshield.config.manager.load_schema",
            return_value={"DATABASE_URL": {"description": "DB URL", "secret": True}},
        )

        with open(".env.local", "w") as f:
            f.write("DATABASE_URL=postgres://user:pass@localhost/db\n")

        mock_console = mocker.patch("envshield.core.schema_manager.console")

        is_in_sync = schema_manager.check_schema(".env.local")

        assert is_in_sync is True
        mock_console.print.assert_any_call(
            "[bold green]✓ Your configuration is perfectly in sync with the schema![/bold green]"
        )


def test_check_schema_out_of_sync(mocker, tmp_path):
    """Tests the check command when the local file is out of sync."""
    with runner.isolated_filesystem(temp_dir=tmp_path):
        mocker.patch(
            "envshield.config.manager.load_schema",
            return_value={"DATABASE_URL": {}, "NEW_VARIABLE": {}},
        )

        with open(".env.local", "w") as f:
            f.write("DATABASE_URL=some_value\nOLD_VARIABLE=true")

        mock_console = mocker.patch("envshield.core.schema_manager.console")

        is_in_sync = schema_manager.check_schema(".env.local")

        assert is_in_sync is False
        assert mock_console.print.call_count > 2


def test_check_schema_flags_a_required_var_declared_but_left_blank(mocker, tmp_path):
    """
    Regression, found via a real incident: a required var (no schema
    default) checked into a Python config module as a blank placeholder --
    e.g. `SECRETS_ENCRYPTION_KEY = ""` ahead of a real per-developer secret
    -- used to be reported as "in sync" because the key's presence was all
    that got checked, never its value. A developer only found out it was
    unset when the app raised at runtime. It must be flagged before that.
    """
    with runner.isolated_filesystem(temp_dir=tmp_path):
        mocker.patch(
            "envshield.config.manager.load_schema",
            return_value={"SECRETS_ENCRYPTION_KEY": {"secret": True}},
        )
        with open("env_config.local.py", "w") as f:
            f.write('SECRETS_ENCRYPTION_KEY = ""\n')

        is_in_sync = schema_manager.check_schema("env_config.local.py")

        assert is_in_sync is False


def test_check_schema_does_not_flag_a_blank_var_that_has_a_default(mocker, tmp_path):
    """A var with a schema default is fine to leave blank locally -- the default covers it."""
    with runner.isolated_filesystem(temp_dir=tmp_path):
        mocker.patch(
            "envshield.config.manager.load_schema",
            return_value={"LOG_LEVEL": {"defaultValue": "info"}},
        )
        with open(".env.local", "w") as f:
            f.write("LOG_LEVEL=\n")

        is_in_sync = schema_manager.check_schema(".env.local")

        assert is_in_sync is True


def test_sync_schema_generates_perfect_file(mocker, tmp_path):
    """Tests that schema sync correctly generates a .env.example file with exact content."""
    with runner.isolated_filesystem(temp_dir=tmp_path) as td:
        schema_data = {
            "DATABASE_URL": {"description": "DB URL", "secret": True},
            "LOG_LEVEL": {"description": "Log verbosity", "defaultValue": "info"},
        }
        mocker.patch("envshield.config.manager.load_schema", return_value=schema_data)

        output_file = os.path.join(td, ".env.example")

        schema_manager.sync_schema()

        assert os.path.exists(output_file)
        with open(output_file, "r") as f:
            content = f.read()

        expected_content = (
            "# It is generated from the contract defined in env.schema.toml.\n"
            "# DO NOT EDIT THIS FILE MANUALLY.\n\n"
            "# DB URL\n"
            "DATABASE_URL=\n\n"
            "# Log verbosity\n"
            "LOG_LEVEL=info\n\n"
        )
        assert expected_content in content


def test_sync_schema_scopes_env_example_to_service_directory(tmp_path, monkeypatch):
    """
    Regression: multiple services syncing from the repo root used to all
    overwrite the same root-level '.env.example', clobbering each other.
    """
    monkeypatch.chdir(tmp_path)
    (tmp_path / "services" / "api").mkdir(parents=True)
    with open("envshield.yml", "w") as f:
        f.write("services:\n  api:\n    path: services/api/env.schema.toml\n")
    with open("services/api/env.schema.toml", "w") as f:
        f.write('[API_KEY]\ndescription="Third-party key"\nsecret=true\n')

    schema_manager.sync_schema(service_name="api")

    assert not os.path.exists(".env.example")
    assert os.path.exists("services/api/.env.example")
    with open("services/api/.env.example") as f:
        assert "API_KEY=" in f.read()


def test_sync_schema_creates_python_local_file_when_missing(tmp_path, monkeypatch):
    """
    A service whose 'local_file' is a Python module (not a dotenv file) gets
    a fresh module generated from the schema, in Python assignment syntax.
    """
    monkeypatch.chdir(tmp_path)
    (tmp_path / "athena" / "config").mkdir(parents=True)
    with open("envshield.yml", "w") as f:
        f.write(
            "services:\n"
            "  athena:\n"
            "    path: athena/env.schema.toml\n"
            "    local_file: athena/config/env_config.local.py\n"
        )
    with open("athena/env.schema.toml", "w") as f:
        f.write(
            '[DB_HOST]\ndescription="Database host"\ndefaultValue="db"\n\n'
            '[API_ADMIN_TOKEN]\ndescription="Admin token"\nsecret=true\n'
        )

    schema_manager.sync_schema(service_name="athena")

    with open("athena/config/env_config.local.py") as f:
        content = f.read()
    assert "DB_HOST = 'db'" in content
    assert "API_ADMIN_TOKEN = ''" in content


def test_sync_schema_appends_missing_vars_to_existing_python_file_without_touching_rest(
    tmp_path, monkeypatch
):
    """
    Regression: this must NOT regenerate the whole file the way '.env.example'
    sync does -- a hand-maintained Python config module can contain real
    logic (imports, conditionals) beyond simple assignments, and a full
    rewrite would destroy it. Only variables missing from the file should be
    appended; everything else -- including an already-set value that
    happens to be blank -- is left completely alone.
    """
    monkeypatch.chdir(tmp_path)
    (tmp_path / "athena" / "config").mkdir(parents=True)
    with open("envshield.yml", "w") as f:
        f.write(
            "services:\n"
            "  athena:\n"
            "    path: athena/env.schema.toml\n"
            "    local_file: athena/config/env_config.local.py\n"
        )
    with open("athena/env.schema.toml", "w") as f:
        f.write(
            '[DB_HOST]\ndescription="Database host"\ndefaultValue="db"\n\n'
            '[INTREPID_KEY]\ndescription="Intrepid API key"\nsecret=true\n\n'
            '[NEW_FEATURE_FLAG]\ndescription="Newly added var"\ndefaultValue="no"\n'
        )
    existing_content = (
        "import os\n\n"
        'DB_HOST = "db"\n'
        'INTREPID_KEY = ""\n\n'
        'if os.environ.get("USE_LOCAL_DB") == "yes":\n'
        '    DB_HOST = "db"\n'
    )
    with open("athena/config/env_config.local.py", "w") as f:
        f.write(existing_content)

    schema_manager.sync_schema(service_name="athena")

    with open("athena/config/env_config.local.py") as f:
        content = f.read()

    # Existing lines and logic are byte-for-byte untouched...
    assert existing_content in content
    # ...and only the missing variable was appended.
    assert "NEW_FEATURE_FLAG = 'no'" in content


def test_sync_schema_reports_when_python_file_already_declares_everything(
    tmp_path, monkeypatch
):
    monkeypatch.chdir(tmp_path)
    (tmp_path / "athena").mkdir(parents=True)
    with open("envshield.yml", "w") as f:
        f.write(
            "services:\n"
            "  athena:\n"
            "    path: athena/env.schema.toml\n"
            "    local_file: athena/env_config.local.py\n"
        )
    with open("athena/env.schema.toml", "w") as f:
        f.write('[DB_HOST]\ndescription="x"\ndefaultValue="db"\n')
    with open("athena/env_config.local.py", "w") as f:
        f.write('DB_HOST = "db"\n')

    with open("athena/env_config.local.py") as f:
        before = f.read()
    schema_manager.sync_schema(service_name="athena")
    with open("athena/env_config.local.py") as f:
        after = f.read()

    assert before == after


def test_diff_against_schema_reports_clean_result():
    diff = schema_manager.diff_against_schema(
        {"FOO": {"description": "x"}}, {"FOO": "bar"}
    )

    assert diff.is_clean is True
    assert diff.summary() == ""


def test_diff_against_schema_reports_every_category():
    schema = {
        "MISSING": {"description": "x"},
        "BLANK": {"description": "x"},
        "PORT": {"description": "x", "type": "port"},
    }
    local_values = {"BLANK": "", "PORT": "not-a-port", "EXTRA": "y"}

    diff = schema_manager.diff_against_schema(schema, local_values)

    assert diff.is_clean is False
    assert diff.missing == {"MISSING"}
    assert diff.blank == {"BLANK"}
    assert "PORT" in diff.invalid
    assert diff.extra == {"EXTRA"}
    summary = diff.summary()
    assert "MISSING" in summary and "BLANK" in summary and "PORT" in summary and "EXTRA" in summary


def test_check_schema_flags_an_invalid_enum_value(mocker, tmp_path):
    with runner.isolated_filesystem(temp_dir=tmp_path):
        mocker.patch(
            "envshield.config.manager.load_schema",
            return_value={"LOG_LEVEL": {"enum": ["debug", "info", "warn", "error"]}},
        )
        with open(".env.local", "w") as f:
            f.write("LOG_LEVEL=verbose\n")

        is_in_sync = schema_manager.check_schema(".env.local")

        assert is_in_sync is False


def test_check_schema_flags_an_invalid_port_value(mocker, tmp_path):
    with runner.isolated_filesystem(temp_dir=tmp_path):
        mocker.patch(
            "envshield.config.manager.load_schema",
            return_value={"API_PORT": {"type": "port"}},
        )
        with open(".env.local", "w") as f:
            f.write("API_PORT=999999\n")

        is_in_sync = schema_manager.check_schema(".env.local")

        assert is_in_sync is False


def test_check_schema_passes_a_valid_typed_value(mocker, tmp_path):
    with runner.isolated_filesystem(temp_dir=tmp_path):
        mocker.patch(
            "envshield.config.manager.load_schema",
            return_value={"API_PORT": {"type": "port"}},
        )
        with open(".env.local", "w") as f:
            f.write("API_PORT=8080\n")

        assert schema_manager.check_schema(".env.local") is True


def test_check_schema_required_if_not_triggered_when_condition_unmet(mocker, tmp_path):
    """A var with 'requiredIf' must not be flagged missing when its condition doesn't hold."""
    with runner.isolated_filesystem(temp_dir=tmp_path):
        mocker.patch(
            "envshield.config.manager.load_schema",
            return_value={
                "FEATURE_X_ENABLED": {"defaultValue": "false"},
                "FEATURE_X_API_KEY": {
                    "secret": True,
                    "requiredIf": {"var": "FEATURE_X_ENABLED", "equals": "true"},
                },
            },
        )
        with open(".env.local", "w") as f:
            f.write("FEATURE_X_ENABLED=false\n")

        assert schema_manager.check_schema(".env.local") is True


def test_check_schema_required_if_triggered_when_condition_met(mocker, tmp_path):
    with runner.isolated_filesystem(temp_dir=tmp_path):
        mocker.patch(
            "envshield.config.manager.load_schema",
            return_value={
                "FEATURE_X_ENABLED": {"defaultValue": "false"},
                "FEATURE_X_API_KEY": {
                    "secret": True,
                    "requiredIf": {"var": "FEATURE_X_ENABLED", "equals": "true"},
                },
            },
        )
        with open(".env.local", "w") as f:
            f.write("FEATURE_X_ENABLED=true\n")

        assert schema_manager.check_schema(".env.local") is False


def test_check_schema_against_docker_compose_file(mocker, tmp_path):
    """A docker-compose file can be validated the same way a plain .env file can."""
    with runner.isolated_filesystem(temp_dir=tmp_path):
        mocker.patch(
            "envshield.config.manager.load_schema",
            return_value={
                "DATABASE_URL": {"secret": True},
                "REDIS_URL": {"secret": False},
            },
        )
        with open("docker-compose.yml", "w") as f:
            f.write(
                "services:\n"
                "  api:\n"
                "    image: myorg/api\n"
                "    environment:\n"
                "      - DATABASE_URL=postgres://user:pass@db/app\n"
            )

        is_in_sync = schema_manager.check_schema("docker-compose.yml")

        # REDIS_URL is genuinely missing from the manifest.
        assert is_in_sync is False


def test_check_schema_against_docker_compose_requires_container_when_ambiguous(mocker, tmp_path):
    with runner.isolated_filesystem(temp_dir=tmp_path):
        mocker.patch("envshield.config.manager.load_schema", return_value={})
        with open("docker-compose.yml", "w") as f:
            f.write(
                "services:\n"
                "  api:\n"
                "    image: myorg/api\n"
                "  worker:\n"
                "    image: myorg/worker\n"
            )

        is_in_sync = schema_manager.check_schema("docker-compose.yml")

        assert is_in_sync is False


def test_check_schema_against_docker_compose_with_explicit_container(mocker, tmp_path):
    with runner.isolated_filesystem(temp_dir=tmp_path):
        mocker.patch(
            "envshield.config.manager.load_schema",
            return_value={"REDIS_URL": {"secret": False}},
        )
        with open("docker-compose.yml", "w") as f:
            f.write(
                "services:\n"
                "  api:\n"
                "    image: myorg/api\n"
                "    environment:\n"
                "      - DATABASE_URL=postgres://user:pass@db/app\n"
                "  worker:\n"
                "    image: myorg/worker\n"
                "    environment:\n"
                "      - REDIS_URL=redis://cache:6379\n"
            )

        is_in_sync = schema_manager.check_schema("docker-compose.yml", container="worker")

        assert is_in_sync is True


def test_check_schema_against_kubernetes_deployment_manifest(mocker, tmp_path):
    with runner.isolated_filesystem(temp_dir=tmp_path):
        mocker.patch(
            "envshield.config.manager.load_schema",
            return_value={"DATABASE_URL": {"secret": True}, "LOG_LEVEL": {"secret": False}},
        )
        with open("deployment.yaml", "w") as f:
            f.write(
                "apiVersion: apps/v1\n"
                "kind: Deployment\n"
                "metadata:\n"
                "  name: api\n"
                "spec:\n"
                "  template:\n"
                "    spec:\n"
                "      containers:\n"
                "        - name: api\n"
                "          env:\n"
                "            - name: DATABASE_URL\n"
                "              valueFrom:\n"
                "                secretKeyRef:\n"
                "                  name: db-secret\n"
                "                  key: url\n"
                "            - name: LOG_LEVEL\n"
                "              value: info\n"
            )

        is_in_sync = schema_manager.check_schema("deployment.yaml")

        assert is_in_sync is True


def test_check_schema_against_kubernetes_manifest_flags_missing_var(mocker, tmp_path):
    with runner.isolated_filesystem(temp_dir=tmp_path):
        mocker.patch(
            "envshield.config.manager.load_schema",
            return_value={"DATABASE_URL": {"secret": True}, "LOG_LEVEL": {"secret": False}},
        )
        with open("deployment.yaml", "w") as f:
            f.write(
                "apiVersion: apps/v1\n"
                "kind: Deployment\n"
                "metadata:\n"
                "  name: api\n"
                "spec:\n"
                "  template:\n"
                "    spec:\n"
                "      containers:\n"
                "        - name: api\n"
                "          env:\n"
                "            - name: LOG_LEVEL\n"
                "              value: info\n"
            )

        is_in_sync = schema_manager.check_schema("deployment.yaml")

        assert is_in_sync is False
