# envshield/tests/core/test_schema_manager.py
import ast
import os
import stat

import pytest
from typer.testing import CliRunner

from envshield.config import manager as config_manager
from envshield.config.manager import SCHEMA_FILE_NAME
from envshield.core import schema_manager
from envshield.core.exceptions import EnvShieldException

runner = CliRunner()


def test_check_schema_in_sync(mocker, tmp_path):
    """Tests the check command when the local file is in sync with the schema."""
    with runner.isolated_filesystem(temp_dir=tmp_path):
        mocker.patch(
            "envshield.config.manager.load_schema",
            return_value={"DATABASE_URL": {"description": "DB URL", "secret": True}},
        )

        with open(".env.local", "w") as f:
            f.write("DATABASE_URL=postgres://user:pass@localhost/db\n")

        mock_console = mocker.patch("envshield.core.schema_manager.console")

        is_in_sync = schema_manager.check_schema(".env.local", service_name="app")

        assert is_in_sync is True
        mock_console.print.assert_any_call(
            "[bold green]✓ Your configuration is perfectly in sync with the schema![/bold green]"
        )


def test_check_schema_out_of_sync(mocker, tmp_path):
    """Tests the check command when the local file is out of sync."""
    with runner.isolated_filesystem(temp_dir=tmp_path):
        mocker.patch(
            "envshield.config.manager.load_schema",
            return_value={"DATABASE_URL": {}, "NEW_VARIABLE": {}},
        )

        with open(".env.local", "w") as f:
            f.write("DATABASE_URL=some_value\nOLD_VARIABLE=true")

        mock_console = mocker.patch("envshield.core.schema_manager.console")

        is_in_sync = schema_manager.check_schema(".env.local", service_name="app")

        assert is_in_sync is False
        assert mock_console.print.call_count > 2


def test_check_schema_flags_a_required_var_declared_but_left_blank(mocker, tmp_path):
    """
    Regression, found via a real incident: a required var (no schema
    default) checked into a Python config module as a blank placeholder --
    e.g. `SECRETS_ENCRYPTION_KEY = ""` ahead of a real per-developer secret
    -- used to be reported as "in sync" because the key's presence was all
    that got checked, never its value. A developer only found out it was
    unset when the app raised at runtime. It must be flagged before that.
    """
    with runner.isolated_filesystem(temp_dir=tmp_path):
        mocker.patch(
            "envshield.config.manager.load_schema",
            return_value={"SECRETS_ENCRYPTION_KEY": {"secret": True}},
        )
        with open("env_config.local.py", "w") as f:
            f.write('SECRETS_ENCRYPTION_KEY = ""\n')

        is_in_sync = schema_manager.check_schema(
            "env_config.local.py", service_name="app"
        )

        assert is_in_sync is False


def test_check_schema_flags_a_blank_var_that_has_a_default(mocker, tmp_path):
    """
    A blank value is worse than an absent one: os.getenv("X", "default")
    only falls back to "default" when the key is missing entirely -- a
    present-but-empty key returns "" instead. A schema default is a
    starting value 'setup' writes automatically, not license for the
    local file's own copy to be silently blank.
    """
    with runner.isolated_filesystem(temp_dir=tmp_path):
        mocker.patch(
            "envshield.config.manager.load_schema",
            return_value={"LOG_LEVEL": {"defaultValue": "info"}},
        )
        with open(".env.local", "w") as f:
            f.write("LOG_LEVEL=\n")

        is_in_sync = schema_manager.check_schema(".env.local", service_name="app")

        assert is_in_sync is False


def test_sync_schema_generates_perfect_file(mocker, tmp_path):
    """Tests that schema sync correctly generates a .env.example file with exact content."""
    with runner.isolated_filesystem(temp_dir=tmp_path) as td:
        schema_data = {
            "DATABASE_URL": {"description": "DB URL", "secret": True},
            "LOG_LEVEL": {"description": "Log verbosity", "defaultValue": "info"},
        }
        mocker.patch("envshield.config.manager.load_schema", return_value=schema_data)
        config_manager.add_service("app", SCHEMA_FILE_NAME)

        output_file = os.path.join(td, ".env.example")

        schema_manager.sync_schema(service_name="app")

        assert os.path.exists(output_file)
        with open(output_file, "r") as f:
            content = f.read()

        expected_content = "# It is generated from the contract defined in env.schema.toml.\n# DO NOT EDIT THIS FILE MANUALLY.\n\n# DB URL\nDATABASE_URL=\n\n# Log verbosity\nLOG_LEVEL=info\n\n"
        assert expected_content in content


def test_sync_schema_warns_before_replacing_pre_existing_non_envshield_example(
    mocker, tmp_path, capsys
):
    """
    Regression, confirmed via real onboarding testing: sync_schema's
    dotenv branch always fully regenerates '.env.example' by design (see
    its own docstring -- it's a pure generated artifact), but a
    pre-existing file that predates EnvShield (no prior EnvShield header)
    used to be replaced with zero signal that hand-written content
    (comments, an intentionally-kept extra variable) was about to be lost.
    A file EnvShield already owns from a prior run should not re-warn on
    every subsequent sync.
    """
    with runner.isolated_filesystem(temp_dir=tmp_path) as td:
        schema_data = {"DATABASE_URL": {"description": "DB URL", "secret": True}}
        mocker.patch("envshield.config.manager.load_schema", return_value=schema_data)
        config_manager.add_service("app", SCHEMA_FILE_NAME)

        output_file = os.path.join(td, ".env.example")
        with open(output_file, "w") as f:
            f.write("# hand-written comment\nDATABASE_URL=\nOLD_FLAG=\n")

        schema_manager.sync_schema(service_name="app")

        warning = capsys.readouterr().out
        assert "already existed" in warning
        assert "will be replaced" in warning

        # A second sync against the now-EnvShield-owned file must not warn again.
        capsys.readouterr()
        schema_manager.sync_schema(service_name="app")
        assert "already existed" not in capsys.readouterr().out


def test_sync_schema_scopes_env_example_to_service_directory(tmp_path, monkeypatch):
    """
    Regression: multiple services syncing from the repo root used to all
    overwrite the same root-level '.env.example', clobbering each other.
    """
    monkeypatch.chdir(tmp_path)
    (tmp_path / "services" / "api").mkdir(parents=True)
    with open("envshield.yml", "w") as f:
        f.write("services:\n  api:\n    schema: services/api/env.schema.toml\n")
    with open("services/api/env.schema.toml", "w") as f:
        f.write('[API_KEY]\ndescription="Third-party key"\nsecret=true\n')

    schema_manager.sync_schema(service_name="api")

    assert not os.path.exists(".env.example")
    assert os.path.exists("services/api/.env.example")
    with open("services/api/.env.example") as f:
        assert "API_KEY=" in f.read()


def test_sync_schema_creates_python_local_file_when_missing(tmp_path, monkeypatch):
    """
    A service whose 'local_file' is a Python module (not a dotenv file) gets
    a fresh module generated from the schema, in Python assignment syntax.
    """
    monkeypatch.chdir(tmp_path)
    (tmp_path / "alpha" / "config").mkdir(parents=True)
    with open("envshield.yml", "w") as f:
        f.write(
            "services:\n  alpha:\n    schema: alpha/env.schema.toml\n    local_file: alpha/config/env_config.local.py\n"
        )
    with open("alpha/env.schema.toml", "w") as f:
        f.write(
            '[DB_HOST]\ndescription="Database host"\ndefaultValue="db"\n\n[API_ADMIN_TOKEN]\ndescription="Admin token"\nsecret=true\n'
        )

    schema_manager.sync_schema(service_name="alpha")

    with open("alpha/config/env_config.local.py") as f:
        content = f.read()
    assert "DB_HOST = 'db'" in content
    assert "API_ADMIN_TOKEN = ''" in content


def test_sync_schema_appends_missing_vars_to_existing_python_file_without_touching_rest(
    tmp_path, monkeypatch
):
    """
    Regression: this must NOT regenerate the whole file the way '.env.example'
    sync does -- a hand-maintained Python config module can contain real
    logic (imports, conditionals) beyond simple assignments, and a full
    rewrite would destroy it. Only variables missing from the file should be
    appended; everything else -- including an already-set value that
    happens to be blank -- is left completely alone.
    """
    monkeypatch.chdir(tmp_path)
    (tmp_path / "alpha" / "config").mkdir(parents=True)
    with open("envshield.yml", "w") as f:
        f.write(
            "services:\n  alpha:\n    schema: alpha/env.schema.toml\n    local_file: alpha/config/env_config.local.py\n"
        )
    with open("alpha/env.schema.toml", "w") as f:
        f.write(
            '[DB_HOST]\ndescription="Database host"\ndefaultValue="db"\n\n'
            '[INTREPID_KEY]\ndescription="Intrepid API key"\nsecret=true\n\n'
            '[NEW_FEATURE_FLAG]\ndescription="Newly added var"\ndefaultValue="no"\n'
        )
    existing_content = 'import os\n\nDB_HOST = "db"\nINTREPID_KEY = ""\n\nif os.environ.get("USE_LOCAL_DB") == "yes":\n    DB_HOST = "db"\n'
    with open("alpha/config/env_config.local.py", "w") as f:
        f.write(existing_content)

    schema_manager.sync_schema(service_name="alpha")

    with open("alpha/config/env_config.local.py") as f:
        content = f.read()

    # Existing lines and logic are byte-for-byte untouched...
    assert existing_content in content
    # ...and only the missing variable was appended.
    assert "NEW_FEATURE_FLAG = 'no'" in content


def test_sync_schema_reports_when_python_file_already_declares_everything(
    tmp_path, monkeypatch
):
    monkeypatch.chdir(tmp_path)
    (tmp_path / "alpha").mkdir(parents=True)
    with open("envshield.yml", "w") as f:
        f.write(
            "services:\n  alpha:\n    schema: alpha/env.schema.toml\n    local_file: alpha/env_config.local.py\n"
        )
    with open("alpha/env.schema.toml", "w") as f:
        f.write('[DB_HOST]\ndescription="x"\ndefaultValue="db"\n')
    with open("alpha/env_config.local.py", "w") as f:
        f.write('DB_HOST = "db"\n')

    with open("alpha/env_config.local.py") as f:
        before = f.read()
    schema_manager.sync_schema(service_name="alpha")
    with open("alpha/env_config.local.py") as f:
        after = f.read()

    assert before == after


def test_diff_against_schema_reports_clean_result():
    diff = schema_manager.diff_against_schema(
        {"FOO": {"description": "x"}}, {"FOO": "bar"}
    )

    assert diff.is_clean is True
    assert diff.summary() == ""


def test_diff_against_schema_does_not_flag_an_unresolved_value_as_invalid():
    """
    Regression, part of the DI-2 fix: a value a parser can't statically
    know (BaseParser.UNRESOLVED_VALUE -- an env_file reference, a bare
    shell pass-through, a Kubernetes secretRef, or an unresolvable Compose
    interpolation) must never be validated against a declared type/enum/
    pattern -- the placeholder string itself would fail any real
    constraint, misreporting a legitimately-unknown value as invalid
    every time a manifest used one of these forms for a typed variable.
    """
    from envshield.parsers._base import BaseParser

    schema = {"API_BASE_URL": {"description": "x", "type": "url"}}

    diff = schema_manager.diff_against_schema(
        schema, {"API_BASE_URL": BaseParser.UNRESOLVED_VALUE}
    )

    assert diff.is_clean is True
    assert diff.invalid == {}


def test_diff_against_schema_flags_defaulted_vars_missing_from_local():
    """
    Regression: a schema variable with a defaultValue, absent from the
    local file entirely, used to be silently accepted as "in sync" --
    nothing guarantees whatever reads this file actually falls back to the
    schema's documented default, or falls back at all, so its own copy has
    to be explicit. Real repro: LOG_LEVEL declared with defaultValue="info",
    never added to a developer's own .env after a schema update.
    """
    schema = {"LOG_LEVEL": {"description": "x", "defaultValue": "info"}}

    diff = schema_manager.diff_against_schema(schema, {})

    assert diff.is_clean is False
    assert diff.missing == {"LOG_LEVEL"}
    assert "LOG_LEVEL" in diff.summary()


def test_diff_against_schema_defaulted_vars_required_regardless_of_requiredif():
    """
    A defaulted variable must be present even if it also happens to carry
    a requiredIf condition that isn't currently active -- the default
    makes it meaningful in every case. A var with neither a default nor an
    active requiredIf condition is the only one still genuinely optional.
    """
    schema = {
        "FLAG": {"description": "x", "defaultValue": "false"},
        "DEPENDENT": {
            "description": "x",
            "requiredIf": {"var": "FLAG", "equals": "true"},
        },
    }

    diff = schema_manager.diff_against_schema(schema, {})

    assert diff.missing == {"FLAG"}
    assert "DEPENDENT" not in diff.missing


def test_check_schema_flags_defaulted_vars_missing_from_local(mocker, tmp_path):
    with runner.isolated_filesystem(temp_dir=tmp_path):
        mocker.patch(
            "envshield.config.manager.load_schema",
            return_value={
                "API_KEY": {"secret": True},
                "LOG_LEVEL": {"defaultValue": "info"},
            },
        )
        with open(".env.local", "w") as f:
            f.write("API_KEY=abc123\n")

        is_in_sync = schema_manager.check_schema(".env.local", service_name="app")

        assert is_in_sync is False


def test_check_result_json_flags_defaulted_vars_missing_from_local(
    tmp_path, monkeypatch
):
    monkeypatch.chdir(tmp_path)
    config_manager.add_service("app", SCHEMA_FILE_NAME)
    with open(SCHEMA_FILE_NAME, "w") as f:
        f.write('[LOG_LEVEL]\ndescription="x"\ndefaultValue="info"\n')
    with open(".env", "w") as f:
        f.write("")

    result = schema_manager.check_result(".env", service_name="app")

    assert result["clean"] is False
    assert result["missing"] == ["LOG_LEVEL"]


class TestUnresolvedSource:
    """
    Regression coverage for the Kubernetes envFrom external-reference gap:
    a required variable this source's own unresolved envFrom reference
    might supply must be reported as unresolved -- neither confidently
    satisfied (it's not in local_values at all) nor confidently missing
    (the reference could be supplying it right now).
    """

    def test_a_required_var_absent_with_an_unresolved_source_is_unresolved_not_missing(
        self,
    ):
        """Requirement #5 and #6: not confidently satisfied, and not reported as definitely absent."""
        schema = {"DATABASE_URL": {"description": "x"}}

        diff = schema_manager.diff_against_schema(
            schema, {}, has_unresolved_source=True
        )

        assert diff.is_clean is False  # not confidently satisfied
        assert diff.missing == set()  # not reported as definitely absent
        assert diff.unresolved == {"DATABASE_URL"}
        assert "DATABASE_URL" in diff.summary()
        assert "Missing" not in diff.summary()
        assert "Cannot confirm" in diff.summary()

    def test_the_same_scenario_without_an_unresolved_source_is_still_plain_missing(
        self,
    ):
        """Default (has_unresolved_source=False) behavior is completely unaffected -- every other parser."""
        schema = {"DATABASE_URL": {"description": "x"}}

        diff = schema_manager.diff_against_schema(schema, {})

        assert diff.missing == {"DATABASE_URL"}
        assert diff.unresolved == set()

    def test_a_variable_actually_present_is_not_marked_unresolved_even_with_an_unresolved_source(
        self,
    ):
        """An unresolved reference elsewhere doesn't cast doubt on a variable EnvShield DOES see."""
        schema = {"DATABASE_URL": {"description": "x"}}

        diff = schema_manager.diff_against_schema(
            schema, {"DATABASE_URL": "postgres://x"}, has_unresolved_source=True
        )

        assert diff.unresolved == set()
        assert diff.is_clean is True

    def test_unresolved_does_not_affect_blank_or_invalid_classification(self):
        """A required var present but blank is still 'blank', not 'unresolved' -- EnvShield DOES know its state."""
        schema = {"DATABASE_URL": {"description": "x"}}

        diff = schema_manager.diff_against_schema(
            schema, {"DATABASE_URL": ""}, has_unresolved_source=True
        )

        assert diff.blank == {"DATABASE_URL"}
        assert diff.unresolved == set()


def test_check_result_json_reports_unresolved_for_a_kubernetes_external_env_from(
    tmp_path, monkeypatch
):
    """
    End-to-end requirement #9: --json surfaces the same unresolved state
    the Rich path does, via an additive 'unresolved' key.
    """
    monkeypatch.chdir(tmp_path)
    config_manager.add_service("api", SCHEMA_FILE_NAME)
    with open(SCHEMA_FILE_NAME, "w") as f:
        f.write('[DATABASE_URL]\ndescription = "x"\n')
    with open("deployment.yaml", "w") as f:
        f.write(
            "apiVersion: apps/v1\n"
            "kind: Deployment\n"
            "metadata:\n  name: api\n"
            "spec:\n"
            "  template:\n"
            "    spec:\n"
            "      containers:\n"
            "        - name: api\n"
            "          envFrom:\n"
            "            - secretRef:\n"
            "                name: externally-managed-secret\n"
        )

    result = schema_manager.check_result("deployment.yaml", service_name="api")

    assert result["clean"] is False
    assert result["unresolved"] == ["DATABASE_URL"]
    assert result["missing"] == []


def test_check_schema_rich_output_reports_cannot_confirm_not_missing(
    tmp_path, monkeypatch, capsys
):
    """
    End-to-end requirement #9: the Rich table path renders the same
    unresolved state as the JSON path, via a distinct 'Cannot Confirm'
    row rather than 'Missing in Local'.
    """
    monkeypatch.chdir(tmp_path)
    config_manager.add_service("api", SCHEMA_FILE_NAME)
    with open(SCHEMA_FILE_NAME, "w") as f:
        f.write('[DATABASE_URL]\ndescription = "x"\n')
    with open("deployment.yaml", "w") as f:
        f.write(
            "apiVersion: apps/v1\n"
            "kind: Deployment\n"
            "metadata:\n  name: api\n"
            "spec:\n"
            "  template:\n"
            "    spec:\n"
            "      containers:\n"
            "        - name: api\n"
            "          envFrom:\n"
            "            - secretRef:\n"
            "                name: externally-managed-secret\n"
        )

    is_in_sync = schema_manager.check_schema("deployment.yaml", service_name="api")

    output = capsys.readouterr().out
    assert is_in_sync is False
    assert "Cannot Confirm" in output
    assert "Missing in Local" not in output


def test_diff_against_schema_reports_every_category():
    schema = {
        "MISSING": {"description": "x"},
        "BLANK": {"description": "x"},
        "PORT": {"description": "x", "type": "port"},
    }
    local_values = {"BLANK": "", "PORT": "not-a-port", "EXTRA": "y"}

    diff = schema_manager.diff_against_schema(schema, local_values)

    assert diff.is_clean is False
    assert diff.missing == {"MISSING"}
    assert diff.blank == {"BLANK"}
    assert "PORT" in diff.invalid
    assert diff.extra == {"EXTRA"}
    summary = diff.summary()
    assert (
        "MISSING" in summary
        and "BLANK" in summary
        and "PORT" in summary
        and "EXTRA" in summary
    )


def test_check_schema_flags_an_invalid_enum_value(mocker, tmp_path):
    with runner.isolated_filesystem(temp_dir=tmp_path):
        mocker.patch(
            "envshield.config.manager.load_schema",
            return_value={"LOG_LEVEL": {"enum": ["debug", "info", "warn", "error"]}},
        )
        with open(".env.local", "w") as f:
            f.write("LOG_LEVEL=verbose\n")

        is_in_sync = schema_manager.check_schema(".env.local", service_name="app")

        assert is_in_sync is False


def test_check_schema_flags_an_invalid_port_value(mocker, tmp_path):
    with runner.isolated_filesystem(temp_dir=tmp_path):
        mocker.patch(
            "envshield.config.manager.load_schema",
            return_value={"API_PORT": {"type": "port"}},
        )
        with open(".env.local", "w") as f:
            f.write("API_PORT=999999\n")

        is_in_sync = schema_manager.check_schema(".env.local", service_name="app")

        assert is_in_sync is False


def test_check_schema_passes_a_valid_typed_value(mocker, tmp_path):
    with runner.isolated_filesystem(temp_dir=tmp_path):
        mocker.patch(
            "envshield.config.manager.load_schema",
            return_value={"API_PORT": {"type": "port"}},
        )
        with open(".env.local", "w") as f:
            f.write("API_PORT=8080\n")

        assert schema_manager.check_schema(".env.local", service_name="app") is True


def test_check_schema_required_if_not_triggered_when_condition_unmet(mocker, tmp_path):
    """A var with 'requiredIf' must not be flagged missing when its condition doesn't hold."""
    with runner.isolated_filesystem(temp_dir=tmp_path):
        mocker.patch(
            "envshield.config.manager.load_schema",
            return_value={
                "FEATURE_X_ENABLED": {"defaultValue": "false"},
                "FEATURE_X_API_KEY": {
                    "secret": True,
                    "requiredIf": {"var": "FEATURE_X_ENABLED", "equals": "true"},
                },
            },
        )
        with open(".env.local", "w") as f:
            f.write("FEATURE_X_ENABLED=false\n")

        assert schema_manager.check_schema(".env.local", service_name="app") is True


def test_check_schema_required_if_triggered_when_condition_met(mocker, tmp_path):
    with runner.isolated_filesystem(temp_dir=tmp_path):
        mocker.patch(
            "envshield.config.manager.load_schema",
            return_value={
                "FEATURE_X_ENABLED": {"defaultValue": "false"},
                "FEATURE_X_API_KEY": {
                    "secret": True,
                    "requiredIf": {"var": "FEATURE_X_ENABLED", "equals": "true"},
                },
            },
        )
        with open(".env.local", "w") as f:
            f.write("FEATURE_X_ENABLED=true\n")

        assert schema_manager.check_schema(".env.local", service_name="app") is False


def test_check_schema_against_docker_compose_file(mocker, tmp_path):
    """A docker-compose file can be validated the same way a plain .env file can."""
    with runner.isolated_filesystem(temp_dir=tmp_path):
        mocker.patch(
            "envshield.config.manager.load_schema",
            return_value={
                "DATABASE_URL": {"secret": True},
                "REDIS_URL": {"secret": False},
            },
        )
        with open("docker-compose.yml", "w") as f:
            f.write(
                "services:\n  api:\n    image: myorg/api\n    environment:\n      - DATABASE_URL=postgres://user:pass@db/app\n"
            )

        is_in_sync = schema_manager.check_schema(
            "docker-compose.yml", service_name="app"
        )

        # REDIS_URL is genuinely missing from the manifest.
        assert is_in_sync is False


def test_check_schema_against_docker_compose_with_interpolated_values(mocker, tmp_path):
    """
    End-to-end DI-2 regression, reproducing exactly the false positive
    found against a real multi-service project: a Compose file using
    '${VAR:-default}' interpolation for a typed variable used to fail
    validation against the literal, un-interpolated template text.
    """
    with runner.isolated_filesystem(temp_dir=tmp_path):
        mocker.patch(
            "envshield.config.manager.load_schema",
            return_value={"API_BASE_URL": {"type": "url"}},
        )
        with open("docker-compose.yml", "w") as f:
            f.write(
                "services:\n"
                "  frontend:\n"
                "    image: myorg/frontend\n"
                "    environment:\n"
                "      - API_BASE_URL=${API_BASE_URL:-https://api.internal}\n"
            )

        is_in_sync = schema_manager.check_schema(
            "docker-compose.yml", service_name="app"
        )

        assert is_in_sync is True


def test_check_schema_against_docker_compose_requires_container_when_ambiguous(
    mocker, tmp_path
):
    with runner.isolated_filesystem(temp_dir=tmp_path):
        mocker.patch("envshield.config.manager.load_schema", return_value={})
        with open("docker-compose.yml", "w") as f:
            f.write(
                "services:\n  api:\n    image: myorg/api\n  worker:\n    image: myorg/worker\n"
            )

        is_in_sync = schema_manager.check_schema(
            "docker-compose.yml", service_name="app"
        )

        assert is_in_sync is False


def test_check_schema_against_docker_compose_with_explicit_container(mocker, tmp_path):
    with runner.isolated_filesystem(temp_dir=tmp_path):
        mocker.patch(
            "envshield.config.manager.load_schema",
            return_value={"REDIS_URL": {"secret": False}},
        )
        with open("docker-compose.yml", "w") as f:
            f.write(
                "services:\n"
                "  api:\n"
                "    image: myorg/api\n"
                "    environment:\n"
                "      - DATABASE_URL=postgres://user:pass@db/app\n"
                "  worker:\n"
                "    image: myorg/worker\n"
                "    environment:\n"
                "      - REDIS_URL=redis://cache:6379\n"
            )

        is_in_sync = schema_manager.check_schema(
            "docker-compose.yml", service_name="app", container="worker"
        )

        assert is_in_sync is True


def test_check_schema_against_kubernetes_deployment_manifest(mocker, tmp_path):
    with runner.isolated_filesystem(temp_dir=tmp_path):
        mocker.patch(
            "envshield.config.manager.load_schema",
            return_value={
                "DATABASE_URL": {"secret": True},
                "LOG_LEVEL": {"secret": False},
            },
        )
        with open("deployment.yaml", "w") as f:
            f.write(
                "apiVersion: apps/v1\n"
                "kind: Deployment\n"
                "metadata:\n"
                "  name: api\n"
                "spec:\n"
                "  template:\n"
                "    spec:\n"
                "      containers:\n"
                "        - name: api\n"
                "          env:\n"
                "            - name: DATABASE_URL\n"
                "              valueFrom:\n"
                "                secretKeyRef:\n"
                "                  name: db-secret\n"
                "                  key: url\n"
                "            - name: LOG_LEVEL\n"
                "              value: info\n"
            )

        is_in_sync = schema_manager.check_schema("deployment.yaml", service_name="app")

        assert is_in_sync is True


def test_check_schema_against_kubernetes_manifest_flags_missing_var(mocker, tmp_path):
    with runner.isolated_filesystem(temp_dir=tmp_path):
        mocker.patch(
            "envshield.config.manager.load_schema",
            return_value={
                "DATABASE_URL": {"secret": True},
                "LOG_LEVEL": {"secret": False},
            },
        )
        with open("deployment.yaml", "w") as f:
            f.write(
                "apiVersion: apps/v1\n"
                "kind: Deployment\n"
                "metadata:\n"
                "  name: api\n"
                "spec:\n"
                "  template:\n"
                "    spec:\n"
                "      containers:\n"
                "        - name: api\n"
                "          env:\n"
                "            - name: LOG_LEVEL\n"
                "              value: info\n"
            )

        is_in_sync = schema_manager.check_schema("deployment.yaml", service_name="app")

        assert is_in_sync is False


class TestSchemaSyncGenerationInjectionIsPrevented:
    """
    Regression coverage for P0-5: a schema key/description is
    repository-controlled (env.schema.toml is committed/PR-editable) and
    lands in a generated '.env.example' or Python local-config module. A
    key is rejected outright -- it's about to become an assignment target,
    and can't be escaped into a safe form without changing its identity.
    A description's embedded newline is escaped instead, since it's data:
    a literal newline would otherwise split a single '# ...' comment into
    an injected extra physical line.
    """

    def test_unsafe_key_is_rejected_before_writing_env_example(self, mocker, tmp_path):
        with runner.isolated_filesystem(temp_dir=tmp_path) as td:
            malicious_key = "GOOD\nENVSHIELD_P0_5_SENTINEL=injected"
            mocker.patch(
                "envshield.config.manager.load_schema",
                return_value={malicious_key: {"description": "x"}},
            )
            config_manager.add_service("app", SCHEMA_FILE_NAME)

            with pytest.raises(EnvShieldException):
                schema_manager.sync_schema(service_name="app")

            assert not os.path.exists(os.path.join(td, ".env.example"))

    def test_unsafe_key_is_rejected_before_writing_python_local_file(
        self, mocker, tmp_path, monkeypatch
    ):
        monkeypatch.chdir(tmp_path)
        (tmp_path / "alpha").mkdir(parents=True)
        with open("envshield.yml", "w") as f:
            f.write(
                "services:\n  alpha:\n    schema: alpha/env.schema.toml\n"
                "    local_file: alpha/env_config.local.py\n"
            )
        with open("alpha/env.schema.toml", "w") as f:
            f.write("")
        malicious_key = "GOOD\nimport os; os.system('true')  #"
        mocker.patch(
            "envshield.config.manager.load_schema",
            return_value={malicious_key: {"description": "x", "defaultValue": "1"}},
        )

        with pytest.raises(EnvShieldException):
            schema_manager.sync_schema(service_name="alpha")

        assert not os.path.exists("alpha/env_config.local.py")

    def test_description_with_embedded_newline_does_not_inject_a_line_into_env_example(
        self, mocker, tmp_path
    ):
        with runner.isolated_filesystem(temp_dir=tmp_path) as td:
            malicious_description = "normal\nENVSHIELD_P0_5_SENTINEL=injected"
            mocker.patch(
                "envshield.config.manager.load_schema",
                return_value={
                    "KEY": {"description": malicious_description, "defaultValue": "v"}
                },
            )
            config_manager.add_service("app", SCHEMA_FILE_NAME)

            schema_manager.sync_schema(service_name="app")

            with open(os.path.join(td, ".env.example")) as f:
                content = f.read()

        lines = content.splitlines()
        sentinel_lines = [line for line in lines if "ENVSHIELD_P0_5_SENTINEL" in line]
        assert len(sentinel_lines) == 1
        # Still part of the '#' comment on one physical line -- never its
        # own standalone KEY=VALUE assignment.
        assert sentinel_lines[0].startswith("#")
        assert "ENVSHIELD_P0_5_SENTINEL=injected" not in lines

    def test_description_with_embedded_newline_does_not_inject_a_python_statement(
        self, mocker, tmp_path, monkeypatch
    ):
        monkeypatch.chdir(tmp_path)
        (tmp_path / "alpha").mkdir(parents=True)
        with open("envshield.yml", "w") as f:
            f.write(
                "services:\n  alpha:\n    schema: alpha/env.schema.toml\n"
                "    local_file: alpha/env_config.local.py\n"
            )
        with open("alpha/env.schema.toml", "w") as f:
            f.write("")
        malicious_description = "normal\nENVSHIELD_P0_5_SENTINEL = True"
        mocker.patch(
            "envshield.config.manager.load_schema",
            return_value={
                "KEY": {"description": malicious_description, "defaultValue": "v"}
            },
        )

        schema_manager.sync_schema(service_name="alpha")

        with open("alpha/env_config.local.py") as f:
            content = f.read()

        # Parsed structurally, not just string-matched -- proves no extra
        # top-level assignment was injected, not merely that "*/"-style
        # text is absent.
        tree = ast.parse(content)
        top_level_names = {
            target.id
            for node in tree.body
            if isinstance(node, ast.Assign)
            for target in node.targets
            if isinstance(target, ast.Name)
        }
        assert "ENVSHIELD_P0_5_SENTINEL" not in top_level_names


class TestNewLocalFilesGetRestrictivePermissions:
    """
    Regression coverage for P1-1. sync_schema's Python-local-file branch
    writes to the same 'local_file' setup writes real secret values into,
    so a freshly-created one must be 0600 -- but its '.env.example'
    branch writes a template explicitly meant to be committed/shared, and
    must NOT be force-restricted, or every project's tracked template
    would come out with unexpectedly narrow permissions.
    """

    def test_fresh_python_local_file_is_created_as_0600(self, tmp_path, monkeypatch):
        monkeypatch.chdir(tmp_path)
        (tmp_path / "alpha").mkdir(parents=True)
        with open("envshield.yml", "w") as f:
            f.write(
                "services:\n  alpha:\n    schema: alpha/env.schema.toml\n"
                "    local_file: alpha/env_config.local.py\n"
            )
        with open("alpha/env.schema.toml", "w") as f:
            f.write('[API_KEY]\ndescription="Admin token"\nsecret=true\n')

        schema_manager.sync_schema(service_name="alpha")

        mode = stat.S_IMODE(os.stat("alpha/env_config.local.py").st_mode)
        assert mode == 0o600

    def test_env_example_template_is_not_restricted_to_0600(self, mocker, tmp_path):
        """
        Control case: '.env.example' is a template, not a secret-bearing
        file -- it must keep its normal, umask-derived permissions, the
        same as before this fix. Compared against an ordinary open()'d
        file created in the same process/umask, rather than a hardcoded
        mode, so this doesn't depend on what the test runner's own umask
        happens to be.
        """
        with runner.isolated_filesystem(temp_dir=tmp_path) as td:
            mocker.patch(
                "envshield.config.manager.load_schema",
                return_value={"API_KEY": {"description": "x", "secret": True}},
            )
            config_manager.add_service("app", SCHEMA_FILE_NAME)

            schema_manager.sync_schema(service_name="app")

            example_mode = stat.S_IMODE(
                os.stat(os.path.join(td, ".env.example")).st_mode
            )
            with open(os.path.join(td, "ordinary-file.txt"), "w") as f:
                f.write("x")
            ordinary_mode = stat.S_IMODE(
                os.stat(os.path.join(td, "ordinary-file.txt")).st_mode
            )
        assert example_mode == ordinary_mode
